name: PHP Composer

on:
  push:
    branches: [ dev ]
  pull_request:
    branches:
      -feature/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Execute tests via PHPUnit
      run: vendor/bin/phpunit
